### ISSUE TITLE
some common issues and suggestion with the latest 1.5.0 library

### ISSUE THREAD

**Issue by kcs-govindtank** [mohamedegy107/youtube_player_embed#5]
Hi @mohamedegy107  great work buddy, while trying this library, I found some issues; 

I am using latest version 1.5.0,  I found some issues which I am listing with possible explanation;

1) Some youtube links are not working;

I am using latest version 1.5.0 
Youtube Video URL : "https://www.youtube.com/watch?v=6CerdjvePsg"
Youtube Video ID: "6CerdjvePsg"

**Error logs:**
"Video element found.", source:  (5)
I/chromium(17414): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'observer' has already been declared", source: https://www.youtube.com/embed/6CerdjvePsg?autoplay=1&mute=0&controls=1&rel=0 (1)

2) Complete Youtube branding removal;
There is mentioned of Youtube branding removal in description of library which is working partially right now, I would suggest if you can get any hint from the package like (y_player), which is completely hiding the Youtube interface., but I would hoping you will improvise the package in a way that in future this can be possible completely. 

3) In iOS, the player is not working tried with debug build in the real device, only showing blank white screen, similar to https://github.com/mohamedegy107/youtube_player_embed/issues/2 

4) Customization option; 
There is no way to customize option to choose for each control which control should be visible or invisible, it would be nice if there is way to place the control position in overall screen based on user requirement.
Just like any other Youtube player library if there is an easy way to have on going playing video's stream available, it will be easy to provide custom external controls.

5) Gesture customization should be there to whether user require the seekto10 seconds in build option or not. there is way to disable it using IgnorePoint widget but it will be nice to have this feature from library it self.

6) Is there any way to disable the suggested content at the end of the video ?

**Comment by mohamedegy107** [comment]
Thanks, bro! I will improve the package further, God willing.

Some YouTube links are not working
→ I will investigate the issue and identify the problem.

Complete YouTube branding removal
→ The package completely removes the YouTube branding. However, if you face any issues with this, please send me a screenshot.

On iOS
→ I have already explained what you should do in this case. If the problem persists, I will gladly help you fix it, God willing.

Customization options
→ You can achieve this using the package. I have implemented a controller and listeners, allowing you to hide the video controllers and build a custom UI. You can then control the video using the package controller. If you mean creating a complete video controller UI, I don’t think I will do that anytime soon.

Gesture customization
→ This is a great idea! I will include it in the next version, God willing.

Is there any way to disable the suggested content?
→ Yes, this feature will be available in the next version, God willing.

**Comment by kcs-govindtank** [comment]
@mohamedegy107  for the  listed number 1 issue, this can be suggestion of solution https://stackoverflow.com/questions/51424578/embed-youtube-code-is-not-working-in-html , but not sure. I hope you can try the provided youtube URL and check for the same.

**Comment by mohamedegy107** [comment]
ios version will fixed god willing now you can try it 
and this video you sent 
https://www.youtube.com/watch?v=6CerdjvePsg
don't play in embed view (this's from youtube) 

thanks bro.

**Comment by kcs-govindtank** [comment]
@mohamedegy107  I checked with version 1.6.0 for iOS platform, the video is still not showing in iOS even after following the setup steps you have recently added

**Comment by mohamedegy107** [comment]
i'm sorry i fixed it and i will tell you here when i upload the new version at the night

**Comment by kcs-govindtank** [comment]
> ios version will fixed god willing now you can try it and this video you sent https://www.youtube.com/watch?v=6CerdjvePsg don't play in embed view (this's from youtube)
> 
> thanks bro.

Is there any other way to play the specified youtube URL, I am looking forward to any alternative to use with this library.  @mohamedegy107 was the following link don't have any solution https://stackoverflow.com/questions/51424578/embed-youtube-code-is-not-working-in-html ?

**Comment by mohamedegy107** [comment]
I'm sorry, but your link cannot be played in embed mode, even on YouTube, because the video owner has disabled embedding.
